default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: face_development
test:
  <<: *default
  database: face_test

production:
  <<: *default
  database: face_production
  username: face
  password: <%= ENV['FACE_DATABASE_PASSWORD'] %>
